[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt-broker:1883"]
  topics = ["temp", "humidity", "distance", "object"]
  data_format = "value"
  data_type = "float"

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "iot"
